name: Docs

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [template-updated]

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  generate-docs:
    uses: silksong-modding/silksong-modding-style-docfx/.github/workflows/build-docs.yml@main
    with:
      environment-name: github-pages
      docs-path: docs
